In [1]:
import tensorflow as tf
import numpy as np

In [20]:
A = np.ones((5, 5))
A = A.reshape((1, 5, 5, 1))

In [3]:
A[0, :, :, 0]

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [4]:
F = np.ones((2, 2)).reshape((2, 2, 1, 1))

In [5]:
F[:, :, 0, 0]

array([[ 1.,  1.],
       [ 1.,  1.]])

In [7]:
g = tf.Graph()
with g.as_default():
    t_input = tf.Variable(A, dtype=tf.float32)
    t_filter = tf.Variable(F, dtype=tf.float32)
    
    #t_output = tf.matmul(t_input, t_input)
    
    sess = tf.Session()
    init = tf.global_variables_initializer()
    sess.run(init)
    
    #import pdb
    #pdb.set_trace()
    t_output = tf.nn.conv2d(t_input, t_filter, strides=[1, 1, 1, 1], padding='SAME')
    
    sess.run(t_output)

In [12]:
B = t_output.eval(session=sess)

In [13]:
B.shape

(1, 5, 5, 1)

In [15]:
B[0, :, :, 0]

array([[ 4.,  4.,  4.,  4.,  2.],
       [ 4.,  4.,  4.,  4.,  2.],
       [ 4.,  4.,  4.,  4.,  2.],
       [ 4.,  4.,  4.,  4.,  2.],
       [ 2.,  2.,  2.,  2.,  1.]], dtype=float32)

In [21]:
g = tf.Graph()
with g.as_default():
    t_input = tf.Variable(A, dtype=tf.float32)
    t_filter = tf.Variable(F, dtype=tf.float32)
    
    sess = tf.Session()
    init = tf.global_variables_initializer()
    sess.run(init)
    
    t_output = tf.nn.conv2d_transpose(
        t_input, t_filter,
        output_shape=(1, 5, 5, 1),
        strides=[1, 1, 1, 1],
        padding='SAME'
    )
    
    sess.run(t_output)

In [22]:
B = t_output.eval(session=sess)

In [23]:
B[0, :, :, 0]

array([[ 1.,  2.,  2.,  2.,  2.],
       [ 2.,  4.,  4.,  4.,  4.],
       [ 2.,  4.,  4.,  4.,  4.],
       [ 2.,  4.,  4.,  4.,  4.],
       [ 2.,  4.,  4.,  4.,  4.]], dtype=float32)

In [26]:
t_output.shape[-1]

Dimension(1)

In [ ]:
import numpy as np
import tensorflow as tf

# Model parameters
W = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
# Model input and output
x = tf.placeholder(tf.float32)
linear_model = W * x + b
y = tf.placeholder(tf.float32)
# loss
loss = tf.reduce_sum(tf.square(linear_model - y)) # sum of the squares
# optimizer
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)
# training data
x_train = [1,2,3,4]
y_train = [0,-1,-2,-3]
# training loop
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init) # reset values to wrong
for i in range(1000):
  sess.run(train, {x:x_train, y:y_train})

# evaluate training accuracy
curr_W, curr_b, curr_loss  = sess.run([W, b, loss], {x:x_train, y:y_train})
print("W: %s b: %s loss: %s"%(curr_W, curr_b, curr_loss))